### PR TITLE
Register *MESSAGES* at runtime rather than macro-expand time

### PR DESCRIPTION
**Pull request by appleby**
Previously, messages defined with `DEFMESSAGE` were only registered in the `*MESSAGES*` table at macro-expansion time. As a result, the `TEST-DEFMESSAGE` test would pass only if the file was stale and needed to be compiled, but runs that merely loaded the pre-compiled FASL would fail.

### CODE REVIEW

**Comment by appleby** [comment]
I'm not sure what's going on with the test runner. Tests pass locally for me. Will look into it.

**Comment by jmbr** [comment]
FWIW, `(asdf:test-system :rpcq)` passes all the test for me.

**Comment by appleby** [comment]
There is no trace output from the runners... wondering if the power outage yesterday affected something.

**Comment by appleby** [comment]
Test runners appear to have sorted themselves out.

**Pull request merged**
