### PR TITLE
Support QRTx2Sequencer message spec.

### PR DESCRIPTION
**Pull request by psivaraj**
Adding support for the QRTx2 sequencer.

### CODE REVIEW

**Comment by ecpeterson** [comment]
A comment on both this PR and #59: the source of truth for the message spec is spread across `src/messages.lisp` and `src/core-messages.lisp`, whereas `rpcq/core_messages.py` is auto-generated by running `update_python_spec.lisp`. You should at least edit both the Lisp and the python sides, but ideally you'd only manually edit the Lisp side and then pick up those edits on the python side using the code generator.

Running the generator directly requires having Lisp installed (cf. https://github.com/rigetti/qvm/blob/master/doc/lisp-setup.md), and I thought there was some clever Docker magic to help FSQErs avoid needing these dependencies, but now I can't find this path. @caryan?

**Comment by ecpeterson** [comment]
That aside, this looks like a fine message.

**Comment by psivaraj** [comment]
> A comment on both this PR and #59: the source of truth for the message spec is spread across `src/messages.lisp` and `src/core-messages.lisp`, whereas `rpcq/core_messages.py` is auto-generated by running `update_python_spec.lisp`. You should at least edit both the Lisp and the python sides, but ideally you'd only manually edit the Lisp side and then pick up those edits on the python side using the code generator.
> 
> Running the generator directly requires having Lisp installed (cf. https://github.com/rigetti/qvm/blob/master/doc/lisp-setup.md), and I thought there was some clever Docker magic to help FSQErs avoid needing these dependencies, but now I can't find this path. @caryan?

Ah sorry, misunderstanding on my part. I thought from a previous conversation w/ @caryan that the lisp specs were blasted away. Will close and re-open.

**Comment by caryan** [comment]
Uh sorry @psivaraj "blasted away" from `pidgin`.

**Pull request closed without merging**
