### PR TITLE
Fix syslog priority

### PR DESCRIPTION
**Pull request by notmgsk**
`':error` -> `':err`

### CODE REVIEW

**Comment by ecp-rigetti** [comment]
Sure enough: https://github.com/mmaul/cl-syslog/blob/0f43aa4f90c0e768b29f08ee540feb64ccb8e57d/variable.lisp#L9 .

**Comment by ecp-rigetti** [comment]
Idk what's up with the GitLab check. I'll ping @karalekas about it but it also looks fine to merge as-is.

**Comment by notmgsk** [comment]
> Idk what's up with the GitLab check. I'll ping @karalekas about it but it also looks fine to merge as-is.

I'm gonna run it again. Looks like there was an issue on gitlab's side.

**Comment by notmgsk** [comment]
No idea why the gitlab pipeline is failing. I can't even push to this branch anymore.

**Comment by ecp-rigetti** [comment]
I see the following in the GitLab output when it's trying to assemble the Lisp base:
```
Err:23 http://deb.debian.org/debian stretch/main amd64 libzmq3-dev amd64 4.2.1-4
  404  Not Found
```
Maybe `libzmq3-dev` got moved (or removed)? At any rate, it's not your fault.

**Pull request merged**
