### PR TITLE
core-messages: Rename flux_relay to relay_closed to match better with…

### PR DESCRIPTION
**Pull request by stephanbro**
… the rest of rest of the system.

### CODE REVIEW

**Comment by notmgsk** [comment]
@stephanbro It just occurred to me that this is not backwards compatible. Is it a hard requirement that you change the name? I worry that we might break something for internal users.

**Comment by stephanbro** [comment]
@notmgsk I'm not sure I follow. My intention with renaming this is because the existing schemes for opening and closing the flux relay uses the term "relay_closed", so I think I broke some of the internal naming originally by calling it "flux_relay". Does that resolve your concern?

**Comment by notmgsk** [comment]
> @notmgsk I'm not sure I follow. My intention with renaming this is because the existing schemes for opening and closing the flux relay uses the term "relay_closed", so I think I broke some of the internal naming originally by calling it "flux_relay". Does that resolve your concern?

My worry is that we have some code somewhere which uses the old name and will have to be updated to use the new name. If you're OK with that (or believe it is a non-issue) then I'm OK with it too.

**Comment by stephanbro** [comment]
I think I wasn't clear in my comment before, but the old name that's used in the rest of the system for this parameter is `relay_closed` (which is what I'm changing the name to). I'll definitely resolve any naming issues if they arise as needed!

**Comment by notmgsk** [comment]
> I think I wasn't clear in my comment before, but the old name that's used in the rest of the system for this parameter is `relay_closed` (which is what I'm changing the name to). I'll definitely resolve any naming issues if they arise as needed!

Ah, now I see.

**Pull request merged**
