### PR TITLE
Deprecate RPCErrorError in favor of RPCError

### PR DESCRIPTION
**Pull request by mpharrigan**
fixes gh-6

### CODE REVIEW

**Comment by mpharrigan** [comment]
I don't have access to the semaphore logs

**Comment by stevenheidel** [comment]
Neither do I... @karalekas ?

**Comment by ecp-rigetti** [comment]
I don't even see rpcq listed as one of our semaphore targets. So secretive

**Comment by ecp-rigetti** [comment]
Robert added me to make sure there weren't any Lisp-facing changes that needed to be made. AFAICT, there aren't. Looks good to go.

**Comment by ecp-rigetti** [comment]
FYI, the Semaphore failure is:
```
rpcq/test/test_rpc.py .execution expired
```

**Comment by karalekas** [comment]
whats going on here?

**Comment by ecp-rigetti** [comment]
I don't know, but I also see this on my local machine if I check out Matt's branch. I can look into it.

**Comment by ecp-rigetti** [comment]
I sent Matt a patch.

**Pull request merged**
